### ISSUE TITLE
Unable to Deploy AWS ServiceBroker onto CFCR

### ISSUE THREAD

**Issue by vadimb111** [cloudfoundry-incubator/kubo-release#290]
**What happened**:
While trying to Deploy AWS Service Broker and following the guide located here:  https://github.com/awslabs/aws-servicebroker/tree/master/docs we've encountered the following problems:

In the logs of catalog-controller-manager we're seeing: 

I0115 18:24:32.111165       1 request.go:942] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
F0115 18:24:32.112390       1 controller_manager.go:233] error running controllers: failed to get api versions from server: failed to get supported resources from server: Unauthorized

In the logs of catalog-apiserver, we're seeing: 

E0115 18:26:36.209253       1 authentication.go:62] Unable to authenticate the request due to an error: x509: subject with cn=master.cfcr.internal is not allowed

**What you expected to happen**:
Service Catalog and Service Broker to be deployed normally

**How to reproduce it (as minimally and precisely as possible)**:
Run:

# Adds the chart repository for the service catalog
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
# Installs the service catalog
helm install svc-cat/catalog --name catalog --namespace catalog

**Anything else we need to know?**:

**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`):
int-vega-cfcr  bosh-dns/1.10.0  bosh-aws-xen-hvm-ubuntu-xenial-go_agent/170.14  4 cloud/default  -
               bpm/1.0.0                                                        2 runtime/dns
               cfcr-etcd/1.8.0
               docker/33.0.0
               kubo/0.26.0
- Environment Info (`bosh -e <environment> environment`):
- Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider (e.g. `aws`, `gcp`, `vsphere`):
aws

**Comment by making** [comment]
Following ops-file works for me as a workround:

```yaml
- type: replace
  path: /instance_groups/name=master/jobs/name=kube-apiserver/properties/k8s-args/requestheader-allowed-names
  value: aggregator,master.cfcr.internal
```

```
$ kubectl get pod -n catalog
NAME                                                  READY   STATUS    RESTARTS   AGE
catalog-catalog-apiserver-74ccfdccb5-k2tsg            2/2     Running   0          68s
catalog-catalog-controller-manager-578b5f4c54-469z6   1/1     Running   2          68s
```

**Comment by saimanoj01** [comment]
@vadimb111 I was not able to reproduce this issue. I was able to deploy the service catalog on aws without any issues.
```$ kubectl get pods -n catalog 
NAME                                                  READY   STATUS    RESTARTS   AGE
catalog-catalog-apiserver-9b9995d44-7z88r             2/2     Running   0          36s
catalog-catalog-controller-manager-844cf9c464-ns44b   1/1     Running   0          36s
```

Deployment Info: 
```
releases:
- name: kubo
  version: 0.29.0
- name: cfcr-etcd
  sha1: deaf11d343ecd732848255355874222d24f41bd2
  url: https://storage.googleapis.com/kubo-precompiled-releases/cfcr-etcd-1.9.0-ubuntu-xenial-250.9-20190213-194350-103049471.tgz
  version: 1.9.0
- name: docker
  sha1: 06678d9672cbd5e2243d10bbd27ac86b4f7627a9
  url: https://storage.googleapis.com/kubo-precompiled-releases/docker-35.0.0-ubuntu-xenial-250.9-20190220-215157-61207336.tgz
  version: 35.0.0
- name: bpm
  sha1: d4480335f743623f6930ff901056b90de073e76d
  url: https://storage.googleapis.com/kubo-precompiled-releases/bpm-1.0.3-ubuntu-xenial-250.9-20190213-195020-853877828.tgz
  version: 1.0.3
```
Kubernetes Version:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud provider : AWS

Ops Files used:
```
manifests/ops-files/misc/single-master.yml
manifests/ops-files/add-hostname-to-master-certificate.yml
manifests/ops-files/misc/scale-to-one-az.yml
manifests/ops-files/kubo-local-release.yml
```

Try with the latest available kubo-release and please let us know the ops-files you used during the deployment of CFCR cluster. And also please provide any additional steps to reproduce.
