### ISSUE TITLE
secret generate for dashboard don't use the right parameter name

### ISSUE THREAD

**Issue by obeyler** [cloudfoundry-incubator/kubo-release#335]
**What happened**:

secret generated for K8S dashboard doesn't respect the ingress controller secret definition and use kubernetes-dashboard-cert, kubernetes-dashboard-key instead of tls.cert, tls.key
see : 

> "The TLS secret must contain keys named tls.crt and tls.key that contain the certificate and private key to use for TLS"

inside official K8S documentation
https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

the code :

https://github.com/cloudfoundry-incubator/kubo-release
/blob/3d1cefe324043dc1c3d93f19665424a55e37d49a/jobs/apply-specs/templates/bin/deploy-specs.erb#L28-L31

will create a secret with 
```
apiVersion: v1
data:
  kubernetes-dashboard-cert: XXXXXX
  kubernetes-dashboard-key: XXXXX
kind: Secret
metadata:
  name: kubernetes-dashboard-certs
  namespace: kube-system
type: Opaque


```
**What you expected to happen**:

will create a secret with 
```
apiVersion: v1
data:
  tls.cert: XXXXXX
  tls.key: XXXXX
kind: Secret
metadata:
  name: kubernetes-dashboard-certs
  namespace: kube-system
type: Opaque
```
