### ISSUE TITLE
Cannot set `clusterDomain` in kubo-deployment

### ISSUE THREAD

**Issue by mxplusb** [cloudfoundry-incubator/kubo-release#359]
**What happened**:

I attempted to change the default cluster domain name.

**What you expected to happen**:

The domain name change in the manifest would be applied.

**How to reproduce it (as minimally and precisely as possible)**:

With this ops file:

```yaml
# custom-domain.yml
---
- type: replace
  path: /instance_groups/name=worker/jobs/name=kubelet/properties/kubelet-configuration/clusterDomain
  value: broomfield.local
- type: replace
  path: /variables/name=tls-kubernetes/options/alternative_names/3:next
  value: kubernetes.default.svc.broomfield.local
```

Using this deployment command:

```sh
bosh -d cfcr deploy -o custom-domain.yml <(curl https://raw.githubusercontent.com/cloudfoundry-incubator/kubo-deployment/v0.36.0/manifests/cfcr.yml)
```

**Anything else we need to know?**:

The bug is in the [coredns spec](https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/apply-specs/templates/specs/coredns.yml.erb#L59). The value is hardcoded instead of reading the config from the manifest, which means it can't be changed.

**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`):

```sh
Name  Release(s)        Stemcell(s)                                      Config(s)          Team(s)
cfcr  bosh-dns/1.12.0   bosh-vsphere-esxi-ubuntu-xenial-go_agent/456.27  2 runtime/default  -
      bpm/1.0.4                                                          1 cloud/default
      cfcr-etcd/1.11.1
      docker/35.3.3
      kubo/0.36.0
```

- Environment Info (`bosh -e <environment> environment`):

```sh
Name               bosh
UUID               c28b9d1b-fbfe-479c-a418-8c757533bc84                                                                           Version            270.5.0 (00000000)                                                                                             Director Stemcell  ubuntu-xenial/456.27                                                                                           CPI                vsphere_cpi                                                                                                    Features           compiled_package_cache: disabled                                                                                                  config_server: enabled
                   local_dns: enabled
                   power_dns: disabled
                   snapshots: disabled
User               admin
```

- Kubernetes version (`kubectl version`): 1.15
- Cloud provider (e.g. `aws`, `gcp`, `vsphere`): vsphere
